name: Create tag on main

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create tag
        run: |
          TAG_NAME=$(date --rfc-3339=date)
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}