name: Deploy image from tag

on:
  push:
    tags:
      - "**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    uses: ./.github/workflows/deploy-image.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      lotus-env-tags: ghcr.io/lotus-env:latest,ghcr.io/lotus-env:${{ github.ref_name }}
      lotus-docs-env-tags: ghcr.io/lotus-docs-env:latest,ghcr.io/lotus-docs-env:${{ github.ref_name }}
