name: Deploy image from tag

on:
  push:
    tags:
      - "**"

jobs:
  build-and-push-image:
    uses: ./.github/workflows/deploy-image.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      version: ${{ github.ref_name }}